#!/usr/bin/env bash
# rsysinfo
# run sysinfo directly from github
# will always have the most up to date version
# put in ~/bin
# chmod +x rsysinfo
# rsysinfo
# September 2022

# update sysinfo
wget -q https://raw.githubusercontent.com/dougpark/RaspberryPi_sysinfo/master/sysinfo 
chmod +x sysinfo >/dev/null 2>&1

# update rsysinfo
wget -q https://raw.githubusercontent.com/dougpark/RaspberryPi_sysinfo/master/rsysinfo 
chmod +x rsysinfo >/dev/null 2>&1

# run sysinfo from github
wget -q -O - https://raw.githubusercontent.com/dougpark/RaspberryPi_sysinfo/master/sysinfo | python3
